env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - standard
  - "prettier/standard"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - jest
rules: { "prettier/prettier": 0 }
